### ISSUE TITLE
Functional data freedom issue: "styles.js" and "app.js" for web-app are in non-source form

### ISSUE THREAD

**Issue by adfeno** [actorapp/actor-platform#228] opened 2016-01-13 12:00 UTC
According to: http://www.gnu.org/philosophy/javascript-trap.html (fourth paragraph)

Even though JavaScript files are source that can be readable, they're not human-readable, as it makes exercising the freedom to study or adapt the software very difficult to the users who which to do so, since the reader would have to study the full programming language, so as to learn all its formatting tricks which are used for performance or resource saving first, then insert spaces and line breaks (or carriage returns, depending on which operating system the user uses), then read the JavaScript code lots of times in order to understand what each variable does and so rename then according to their intended behaviour.

If you didn't understand, here is an example, a simple follow-along using "app.js", where a JavaScript student would try to guess how "app.js" is composed:

    !function(event_or_export_or_expression_or_exit_status)
    	{function time_or_table_or_text(resource_or_recipient_or_release_or_root_or_radius){
		if (number_or_numeric_or_notice[resource_or_recipient_or_release_or_root_or_radius])
			return number_or_numeric_or_notice[resource_or_recipient_or_release_or_root_or_radius].exports
			var integer_or_imaginary_or_image=number_or_numeric_or_notice[resource_or_recipient_or_release_or_root_or_radius]={exports:{},id:resource_or_recipient_or_release_or_root_or_radius,loaded:!1}
			return event_or_export_or_expression_or_exit_status[resource_or_recipient_or_release_or_root_or_radius].call(integer_or_imaginary_or_image.exports,integer_or_imaginary_or_image,integer_or_imaginary_or_image.exports,time_or_table_or_text),integer_or_imaginary_or_image.loaded=!0,integer_or_imaginary_or_image.exports}var number_or_numeric_or_notice={}

Notice: The student that I interviewed had a hard time understanding the last line, this is why he gave me the messy line almost intact.

This was just an example.

I have heard that both "app.js" and "styles.js" are packaged for web use ("webpackaging") so:

*    If the project holds the copyright of the scripts, we must insert the copyright notice in the resulting JavaScript files, along with a source indication (since I can't do it myself, due to not being skilled with JavaScript, specially with web packaging and undoing obfuscated code, I'll come up with a template for both of these).

*    If the project doesn't own the copyright of the scripts, we must make a JavaScript license weblabels page, either static, or adapted to which JavaScript files the server administrator might insert (I'll also make a static template for this page, and provide comments inside it as to how it must be called across the site).

**Comment by adfeno** [comment] 2016-01-13 12:02
Related issue: https://github.com/actorapp/actor-platform/issues/171

**Comment by ex3ndr** [comment] 2016-01-13 12:12
First of all, half of our JS is generated from **Java** with GWT. Other part is compiled with various build tools and it is very unfortunate if we need to serve sources. As non-processes sources can eat several MB, but compressed one are 400kb at most. This is not "obfuscated", this is "compiled" for better performance and less size.

All our sources are open i don't know what to do more.

This issue is considered as duplicate of #171

**Closed by ex3ndr** 2016-01-13 12:12 UTC
