### ISSUE TITLE
make: ar: Argument list too long

### ISSUE THREAD

**Issue by mosqueiro** [actorapp/actor-platform#355] opened 2016-02-05 13:14 UTC
I'm trying to run the command to generate the SDK IOS , but I am getting the following error :
make: ar: Argument list too long

script : buildFramework.sh
```
make: ar: Argument list too long
make: *** [build] Error 1
Command /bin/sh failed with exit code 2

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Build\ and\ Install\ Actor\ Core build/Build/Intermediates/ActorSDK.build/Release-iphonesimulator/ActorSDK.build/Script-066A52091BC4EA95000E606E.sh
(1 failure)
```

**Comment by Daocheng** [comment] 2016-02-06 03:28
I got the same error.

**Comment by liruqi** [comment] 2016-02-12 22:23
Search for "error:". It's always caused by something else, like https://github.com/actorapp/actor-platform/issues/358. Provide full compile log.

**Comment by Daocheng** [comment] 2016-02-15 05:49
Error has been fixed by recent commit.

**Closed** 2016-02-24 20:18 UTC
